# Generated by Django 4.0.3 on 2022-04-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_status_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
