# Generated by Django 4.0.3 on 2022-04-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='status',
            new_name='returned',
        ),
    ]
