# Generated by Django 4.0.3 on 2022-05-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_rename_status_record_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='request',
            new_name='request_fk',
        ),
    ]
